### ISSUE TITLE
not working with bitbucket pipelines

### ISSUE THREAD

**Issue by dharmesh03** [danielcondemarin/serverless-next.js#149]
{ Error: Command failed with exit code 1 (EPERM): ./node_modules/.bin/next build
    at makeError (/root/.serverless/components/registry/npm/serverless-next.js@1.2.0-alpha.0/node_modules/execa/lib/error.js:58:11)
    at handlePromise (/root/.serverless/components/registry/npm/serverless-next.js@1.2.0-alpha.0/node_modules/execa/index.js:112:26)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
  command: './node_modules/.bin/next build',

**Comment by dharmesh03** [comment]
@danielcondemarin I this functionality is already implemented in serverless-component-v2
I mean it is present in this branch `serverless-component-v2`

`https://github.com/danielcondemarin/serverless-next.js/tree/serverless-component-v2`

**Comment by danielcondemarin** [comment]
Closing this. Latest version of the component adds custom build inputs that should solve this issue: https://github.com/danielcondemarin/serverless-next.js#inputs

@dharmesh03 All latest functionality is in the `master` branch
