### ISSUE TITLE
[Serverless Component] - Deploy fails when Lambda configured with a VPC

### ISSUE THREAD

**Issue by dtkelch** [danielcondemarin/serverless-next.js#180]
**Describe the bug**
When a Lambda has been added to a VPC, the deployment fails.

**To Reproduce**
1. Deploy a Next.js app with serverless-next.js component
2. Open the AWS console, and manually attach a VPC to one of the new Lambdas
3. Re-deploy
4. See error:
```
error:
  InvalidLambdaFunctionAssociation: The function cannot have a VPC configuration. Function:[my lambda arn] 
    at Request.extractError (/Users/data/.serverless/components/registry/npm/serverless-next.js@1.3.0/node_modules/aws-sdk/lib/protocol/rest_xml.js:53:29)
    at Request.callListeners (/Users/data/.serverless/components/registry/npm/serverless-next.js@1.3.0/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/data/.serverless/components/registry/npm/serverless-next.js@1.3.0/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/data/.serverless/components/registry/npm/serverless-next.js@1.3.0/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/data/.serverless/components/registry/npm/serverless-next.js@1.3.0/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/data/.serverless/components/registry/npm/serverless-next.js@1.3.0/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/data/.serverless/components/registry/npm/serverless-next.js@1.3.0/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/data/.serverless/components/registry/npm/serverless-next.js@1.3.0/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/data/.serverless/components/registry/npm/serverless-next.js@1.3.0/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/data/.serverless/components/registry/npm/serverless-next.js@1.3.0/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  message: 'The function cannot have a VPC configuration. Function: ' +
    '[my lambda arn]',
  code: 'InvalidLambdaFunctionAssociation',
  time: 2019-10-05T16:31:19.994Z,
  statusCode: 400,
  retryable: false,
  retryDelay: 38.413945280304794
```

**Desktop (please complete the following information):**
 - OS: macOS 10.14
 - Version: `serverless-next.js@1.3.0`

**Expected behavior**
I'm not sure - I'm guessing this is an issue with `serverless` or `aws-sdk`, but I wanted to start here, in case there was anything I could do. Perhaps this library could support specifying a VPC to deploy the Lambdas into?

**Comment by danielcondemarin** [comment]
@dtkelch As you probably suspected this is a limitation on AWS itself, not the next component. Lambda@Edge doesn't support associating with a VPC. 
A VPC lives in a region, Lambda@Edge is distributed globally. Having said that [AWS has been making progress](https://aws.amazon.com/blogs/aws/new-almost-inter-region-vpc-peering/) on interconnecting VPCs globally so wouldn't be surprised if what you need is supported in the future.

**Comment by dtkelch** [comment]
@danielcondemarin Ah, I didn't realize that was the case - I've never used the Lamba@Edge pattern, but your explanation makes perfect sense.

Thank you!
