### ISSUE TITLE
Question: Error while deploying after deleting in AWS

### ISSUE THREAD

**Issue by Mytrill** [danielcondemarin/serverless-next.js#276]
I am having an issue with deployment which I don't really know how to solve.

Here are the steps:
- I successfully deployed my nextjs app to AWS using this project
- I then had some issues and had to delete my Cloudfront distribution in the AWS console (I should have `serverless remove`, lesson learned the hard way...).

Now I can no longer deploy, here are the ways I tried: 
- run `serverless`: error saying that the distribution does not existing
- run `serverless remove`: same error saying that the distribution does not exist), 
- delete my `.serverless` and `.serverless_nextjs` directories, then run `serverless`, here is the error this gives me:
```
error:
  { CloudFrontOriginAccessIdentityAlreadyExists: The caller reference you are using to create the CloudFront origin access identity is associated with another identity.
    at Request.extractError (/Users/anthony/.serverless/components/registry/npm/serverless-next.js@1.8.0/node_modules/aws-sdk/lib/protocol/rest_xml.js:53:29)
    at Request.callListeners (/Users/anthony/.serverless/components/registry/npm/serverless-next.js@1.8.0/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/anthony/.serverless/components/registry/npm/serverless-next.js@1.8.0/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/anthony/.serverless/components/registry/npm/serverless-next.js@1.8.0/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/anthony/.serverless/components/registry/npm/serverless-next.js@1.8.0/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/anthony/.serverless/components/registry/npm/serverless-next.js@1.8.0/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/anthony/.serverless/components/registry/npm/serverless-next.js@1.8.0/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/anthony/.serverless/components/registry/npm/serverless-next.js@1.8.0/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/anthony/.serverless/components/registry/npm/serverless-next.js@1.8.0/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/anthony/.serverless/components/registry/npm/serverless-next.js@1.8.0/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
  message:
   'The caller reference you are using to create the CloudFront origin access identity is associated with another identity.',
  code: 'CloudFrontOriginAccessIdentityAlreadyExists',
  time: 2020-01-06T16:04:06.195Z,
  requestId: '2a4014df-309e-11ea-abf0-f148bf9415cd',
  statusCode: 409,
  retryable: false,
  retryDelay: 60.795119069959604 }
```

I am not even sure the issue actually comes from this package, so I apologize in advance if this is not the case, but I have been stuck for several hours and I cannot find any proper way to proceed.

Thank you in advance for any help.

**Comment by danielcondemarin** [comment]
@Mytrill Try deleting the CloudFront access identity manually ... https://stackoverflow.com/questions/34546835/how-to-delete-an-aws-cloudfront-origin-access-identity. That may help

**Comment by Mytrill** [comment]
It worked! Thank you very much!
If I had know it was that easy I would have asked 5 hours ago...
