### ISSUE TITLE
Can't deploy -- check if "next.config.js" target is set to "serverless"

### ISSUE THREAD

**Issue by epicfaace** [danielcondemarin/serverless-next.js#299]
However, "next.config.js" target _is_ set to "serverless". Sounds kind of like #266 . Here's the repo: https://github.com/TheStanfordDaily/stanforddaily
```
$ sls
  error:
  Error: pages-manifest not found. Check if `next.config.js`
 target is set to 'serverless'
    at CLI.renderError (/home/epicfaace/.nvm/versions/node/v10.19.0/lib/node_modules/serverless/node_modules/@serverless/cli/src/Context.js:319:15)
    at Object.runComponents (/home/epicfaace/.nvm/versions/node/v10.19.0/lib/node_modules/serverless/node_modules/@serverless/cli/src/index.js:218:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  1s › myNextApplication › pages-manifest not found. Check if `next.config.js` target is set to 'serverless'
```

**Comment by danielcondemarin** [comment]
@epicfaace Can you run 

```
next build
ls .next/serverless
```
and the paste the output here, thanks.

**Comment by epicfaace** [comment]
I believe I got this to work now -- don't remember how I came to this issue earlier. Will reopen if I encounter the issue again!

**Comment by mizzb** [comment]
I am facing the same issue.
