### ISSUE TITLE
Cannot find module 'serverless-next.js'

### ISSUE THREAD

**Issue by simundev** [danielcondemarin/serverless-next.js#310]
**Describe the bug**

While trying to deploy my Serverless app that uses serverless-next.js, I get an error message.

**To Reproduce**

Have serverless.yml like this:

```
nextApp:
  component: "serverless-next.js"%
```

have in package.json dependencies:

`"serverless-next.js": "^1.8.0",`

run `yarn install`

OK (node_modules/serverless-next.js is created and exists)

run `yarn build`

OK

run `sls deploy --component=nextApp`

```
error:
  { Error: Cannot find module 'serverless-next.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Template.load (/Users/myuser/.nvm/versions/node/v10.17.0/lib/node_modules/serverless/node_modules/@serverless/core/src/Component.js:108:24) code: 'MODULE_NOT_FOUND' }
```

**Expected behavior**

A deployment of the application to AWS.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version 10.15.2

**Comment by simundev** [comment]
Serverless was installed with `npm install -g serverless`. So it was looking for a global installation of serverless-next.js. When I did `npm install -g serverless-next.js`, the error dissapeared.
