### ISSUE TITLE
Tutorial steps don't work, no idea how to fix

### ISSUE THREAD

**Issue by codetrove-development** [danielcondemarin/serverless-next.js#356]
Hi,

I have followed step by step this tutorial: https://serverless.com/learn/tutorial/deploying-nextjs-on-aws/

However when i run "npx serverless" I get:

```
 error:
  { Error: Command failed with exit code 1 (Unknown system error -1): node_modules/.bin/next build
    at makeError (C:\Users\xxx\.serverless\components\registry\npm\serverless-next.js@1.9.8\node_modules\serverless-next.js\node_modules\execa\lib\error.js:59:11)
    at handlePromise (C:\Users\xxx\.serverless\components\registry\npm\serverless-next.js@1.9.8\node_modules\serverless-next.js\node_modules\execa\index.js:112:26)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
  command: 'node_modules/.bin/next build',
  exitCode: 1,
  exitCodeName: 'Unknown system error -1',
  stdout: '> Info: Loaded env from .env\nCreating an optimized production build...',
  stderr: '\n> Build error occurred\n{ Error: EEXIST: file already exists, mkdir \'C:\\Users\\xxx\\source\\repos\\test-nextjs\\my-app\\.next\'\n  errno: -4075,\n  code: \'EEXIST\',\n  syscall: \'mkdir\',\n  path: \'C:\\\\Users\\\\xxx\\\\source\\\\repos\\\\test-nextjs\\\\my-app\\\\.next\' }',
  all: '> Info: Loaded env from .env\nCreating an optimized production build...\n\n> Build error occurred\n{ Error: EEXIST: file already exists, mkdir \'C:\\Users\\xxx\\source\\repos\\test-nextjs\\my-app\\.next\'\n  errno: -4075,\n  code: \'EEXIST\',\n  syscall: \'mkdir\',\n  path: \'C:\\\\Users\\\\xxx\\\\source\\\\repos\\\\test-nextjs\\\\my-app\\\\.next\' }',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false,
  signal: undefined }

  2s » nextApp » Error: Command failed with exit code 1 (Unknown system error -1): node_modules/.bin/next build
```

I then deleted the .next directory and I get:

```
  error:
  { Error: Command failed with exit code 1 (Unknown system error -1): node_modules/.bin/next build
    at makeError (C:\Users\Mikey\.serverless\components\registry\npm\serverless-next.js@1.9.8\node_modules\serverless-next.js\node_modules\execa\lib\error.js:59:11)
    at handlePromise (C:\Users\Mikey\.serverless\components\registry\npm\serverless-next.js@1.9.8\node_modules\serverless-next.js\node_modules\execa\index.js:112:26)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
  command: 'node_modules/.bin/next build',
  exitCode: 1,
  exitCodeName: 'Unknown system error -1',
  stdout: '> Info: Loaded env from .env\nCreating an optimized production build...',
  stderr: '\n> Build error occurred\n{ Error: EEXIST: file already exists, mkdir \'C:\\Users\\Mikey\\source\\repos\\test-nextjs\\my-app\\.next\'\n  errno: -4075,\n  code: \'EEXIST\',\n  syscall: \'mkdir\',\n  path: \'C:\\\\Users\\\\Mikey\\\\source\\\\repos\\\\test-nextjs\\\\my-app\\\\.next\' }',
  all: '> Info: Loaded env from .env\nCreating an optimized production build...\n\n> Build error occurred\n{ Error: EEXIST: file already exists, mkdir \'C:\\Users\\Mikey\\source\\repos\\test-nextjs\\my-app\\.next\'\n  errno: -4075,\n  code: \'EEXIST\',\n  syscall: \'mkdir\',\n  path: \'C:\\\\Users\\\\Mikey\\\\source\\\\repos\\\\test-nextjs\\\\my-app\\\\.next\' }',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false,
  signal: undefined }

  2s » nextApp » Error: Command failed with exit code 1 (Unknown system error -1): node_modules/.bin/next build
```
If I run npm run dev though and open localhost:3000 it's working fine.

Expected behavior: As per the tutorial - it deploys

Windows 10

No idea what else to try at this point.

**Comment by codetrove-development** [comment]
Right, I was on an old machine and node was way far behind. Excuse me while i find a window to jump out of.
