### ISSUE TITLE
Feature of uploading files to S3

### ISSUE THREAD

**Issue by mbogdan0** [danielcondemarin/serverless-next.js#402]
I'm trying to make a feature of uploading files to S3, so they would be available at the same domain name as my site is.

I need to dynamically upload files (users of site allowed to do it) and I suppose files should be placed at `/public` folder.

I'm not sure I'm doing it right way. I have an endpoint placed in `/pages/api/` and it looks like 

```javascript
const client = new AWS.S3(options);
await client.putObject({
  Bucket: '1tqef5-sdi2vvn',
  Key: 'public/test.txt',
  Body: Buffer.alloc(8),
}).promise();
```

It really creates file test.txt in public folder (I checked on AWS) but it's not available online. All files that were in my project in `public` directory are available, but dynamically files are not.

How can I upload files to S3? I wish they were available on the same domain name as main site.

**Comment by danielcondemarin** [comment]
@mbogdan0 The reason why it's not available is because Lambda@Edge keeps a manifest of which public files are uploaded at build time. So adding more stuff to that folder in S3 is not picked up. 

Instead, you can use CloudFront for this:

# serverless.yml

myNextApplication:
  component: serverless-next.js
  inputs:
    cloudfront
      origins:
        - url: /images
          pathPatterns:
            /my-images/*:
              ttl:  10 # could be any ttl you want

This should result in CloudFront forwarding to the S3 folder "images" any http requests to `my-images/*`. Then you can programatically use your API to upload the images to such folder. 

This CloudFront feature is only available in `1.12.0-alpha.0`. Feel free to reopen if this doesn't solve your problem 👍

**Comment by mbogdan0** [comment]
@danielcondemarin thank you for your reply!
I have tried it but it doesn't work for me.

When I add `cloudfront` field in my _serverless.yml_ file, an error occurs

```
Error: No valid exports main found for '/usr/local/lib/node_modules/serverless/node_modules/uuid'
    at resolveExportsTarget (internal/modules/cjs/loader.js:618:9)
    at applyExports (internal/modules/cjs/loader.js:499:14)
    at resolveExports (internal/modules/cjs/loader.js:548:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:650:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:948:27)
    at Function.Module._load (internal/modules/cjs/loader.js:854:27)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/lib/utils/config/initialSetup.js:4:14)
    at Module._compile (internal/modules/cjs/loader.js:1128:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:983:32)
    at Function.Module._load (internal/modules/cjs/loader.js:891:14)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/lib/utils/config/index.js:12:22)
    at Module._compile (internal/modules/cjs/loader.js:1128:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:983:32)
    at Function.Module._load (internal/modules/cjs/loader.js:891:14)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:4:16)
    at Module._compile (internal/modules/cjs/loader.js:1128:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:983:32)
    at Function.Module._load (internal/modules/cjs/loader.js:891:14)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/lib/Serverless.js:12:23)
    at Module._compile (internal/modules/cjs/loader.js:1128:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:983:32)
    at Function.Module._load (internal/modules/cjs/loader.js:891:14)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/lib/utils/autocomplete.js:3:20)
    at Module._compile (internal/modules/cjs/loader.js:1128:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:983:32)
    at Function.Module._load (internal/modules/cjs/loader.js:891:14)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless.js:42:22)
    at Module._compile (internal/modules/cjs/loader.js:1128:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:983:32)
    at Function.Module._load (internal/modules/cjs/loader.js:891:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

I tried to reinstall `serverless` package (globally)
I tried to run `serverless` command through `npx`
I tried to remove `node_modules` and reinstall packages
Nothing helps.

When I remove `cloudfront` field, everything is ok.

**Comment by danielcondemarin** [comment]
Oh no, this may. have been because cloudfront: was missing a colon(:) ! on the yaml. I've corrected the example above. Please try again 🙂

**Comment by mbogdan0** [comment]
@danielcondemarin 

Thank you, but unfortunately now it throws other error:
```

  error:
  InvalidArgument: The parameter origin ID must be unique.
    at Request.extractError (/Users/bogdan/.serverless/components/registry/npm/serverless-next.js@1.12.0-alpha.0/node_modules/aws-sdk/lib/protocol/rest_xml.js:53:29)
    at Request.callListeners (/Users/bogdan/.serverless/components/registry/npm/serverless-next.js@1.12.0-alpha.0/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/bogdan/.serverless/components/registry/npm/serverless-next.js@1.12.0-alpha.0/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/bogdan/.serverless/components/registry/npm/serverless-next.js@1.12.0-alpha.0/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/bogdan/.serverless/components/registry/npm/serverless-next.js@1.12.0-alpha.0/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/bogdan/.serverless/components/registry/npm/serverless-next.js@1.12.0-alpha.0/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/bogdan/.serverless/components/registry/npm/serverless-next.js@1.12.0-alpha.0/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/bogdan/.serverless/components/registry/npm/serverless-next.js@1.12.0-alpha.0/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/bogdan/.serverless/components/registry/npm/serverless-next.js@1.12.0-alpha.0/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/bogdan/.serverless/components/registry/npm/serverless-next.js@1.12.0-alpha.0/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  message: 'The parameter origin ID must be unique.',
  code: 'InvalidArgument',
  time: 2020-05-15T10:15:50.055Z,
  requestId: '8435368e-a6cf-4269-8741-748e564bc85c',
  statusCode: 400,
  retryable: false,
  retryDelay: 14.786681977086102
}

  49s › myNextApplication › InvalidArgument: The parameter origin ID must be unique.

```

**Comment by danielcondemarin** [comment]
Mmh @gehan any idea what may be causing this? I suspect the expandRelativeUrls S3 origin feature isn’t working as expected.

**Comment by gehan** [comment]
Hm yes perhaps - something probably didn't play nicely when the other PR was merged. Will look at this soon!
